import { library } from '@fortawesome/fontawesome-svg-core'
import { faGetPocket } from '@fortawesome/free-brands-svg-icons'
import { faCoffee, faAngleDoubleDown, faBookmark, faSpinner, faAsterisk, faSync, faUser, faUserCircle, faUserCheck, faCheck, faPlus, faPlusCircle, faFrown, faTruck, faTimesCircle, faTimes, faArrowRight, faClock, faLink, faEdit, faEnvelope, faTrashAlt, faMapMarkerAlt, faTag, faNewspaper, faSun, faCloud, faMoon, faGlassMartini, faQuestion, faTrash, faBan, faExclamationTriangle } from '@fortawesome/free-solid-svg-icons';

library.add(
  faCoffee, 
  faAngleDoubleDown, 
  faBookmark, 
  faGetPocket, 
  faSpinner, 
  faAsterisk, 
  faSync, 
  faUser, 
  faUserCircle,
  faUserCheck,
  faCheck,
  faPlus,
  faPlusCircle,
  faFrown,
  faTruck,
  faTimesCircle,
  faTimes,
  faArrowRight,
  faClock,
  faLink,
  faEdit,
  faCheck,
  faEnvelope,
  faTrashAlt,
  faMapMarkerAlt,
  faTag,
  faNewspaper,
  faSun,
  faCloud,
  faMoon,
  faClock,
  faGlassMartini,
  faQuestion,
  faEnvelope,
  faTrash,
  faBan,
  faExclamationTriangle
);